* README

** To clone this repository

*** Clone the repository:

#+begin_src sh
git clone https://github.com/atanasj/prez_tmp.git YOUR_NEW_REPO
cd YOUR_NEW_REPO
#+end_src

*** Create a new repository on GitHub:

- Go to https://github.com/new.
- Name your new repository.
- Do not initialise with a README, ~.gitignore~, or license file.

*** Set the new repository as your origin:

#+begin_src sh
git remote rename origin upstream
git remote add origin https://github.com/YOUR_USERNAME/YOUR_NEW_REPO.git
#+end_src

*** Push to the new repository:

#+begin_src sh
git push -u origin main
#+end_src

Replace =YOUR_USERNAME= and =YOUR_NEW_REPO= with your GitHub username and the
name of your new repository, respectively.

** To create presentations

Clone this repo, update the [[To host a presentation][link below]], then update the ~index.org~ file as
required.

I use this repository for hosting images or other content that I would like to
embed into presentations that are not available on the public domain in order to
make slide decks transportable, and only require a working internet connection.

Add local resources in the ~./assets~ directory. Alternatively, can copy the
relevant =url= of the resource yo find on the internet and add into the slide
deck appropriately. The latter is particularly recommended for online video
content, e.g., YouTube, which can be embedded into the presentation.


------
** To host a presentation

If you want to have this repo as base for a presentation on GitHub pages, update
the link below. Access the slides by clicking on [[https://atanasj.github.io/prez_tmp/][this link]].

